from __future__ import annotations

import ctypes
import os
import time
from collections.abc import Callable

from PySide6.QtCore import QEvent, QObject, QTimer, Qt, Signal
from PySide6.QtGui import QKeyEvent
from PySide6.QtWidgets import QApplication

ACTION_MINIMAL_WIDGET = "minimal_widget"
ACTION_OPEN_WIDGET = "open_widget"
ACTION_PREVIOUS = "previous"
ACTION_PLAY_PAUSE = "play_pause"
ACTION_NEXT = "next"

# Raw function keys are intentionally NOT radio shortcuts. Windows usually does
# not expose the physical Fn key, so accepting F10/F11/F12 would also trigger on
# a plain key press. We only listen to the distinct multimedia codes emitted by
# a keyboard's Fn layer. Ctrl+Alt+F8/F9 remain a reliable widget fallback.
VK_CONTROL = 0x11
VK_MENU = 0x12
VK_F8 = 0x77
VK_F9 = 0x78
VK_F10 = 0x79
VK_F11 = 0x7A
VK_F12 = 0x7B
VK_MEDIA_NEXT_TRACK = 0xB0
VK_MEDIA_PREV_TRACK = 0xB1
VK_MEDIA_STOP = 0xB2
VK_MEDIA_PLAY_PAUSE = 0xB3
VK_LAUNCH_MEDIA_SELECT = 0xB5

WINDOWS_VIRTUAL_KEY_ACTIONS: dict[int, str] = {
    VK_MEDIA_PLAY_PAUSE: ACTION_PLAY_PAUSE,
    VK_MEDIA_PREV_TRACK: ACTION_PREVIOUS,
    VK_MEDIA_NEXT_TRACK: ACTION_NEXT,
    # Some laptop/compact-keyboard Fn layers expose F8/F9 as these distinct
    # media commands. They are safe because bare F8/F9 are never accepted.
    VK_MEDIA_STOP: ACTION_MINIMAL_WIDGET,
    VK_LAUNCH_MEDIA_SELECT: ACTION_OPEN_WIDGET,
}

QT_KEY_ACTIONS: dict[int, str] = {
    int(Qt.Key.Key_MediaTogglePlayPause): ACTION_PLAY_PAUSE,
    int(Qt.Key.Key_MediaPlay): ACTION_PLAY_PAUSE,
    int(Qt.Key.Key_MediaPause): ACTION_PLAY_PAUSE,
    int(Qt.Key.Key_MediaPrevious): ACTION_PREVIOUS,
    int(Qt.Key.Key_MediaNext): ACTION_NEXT,
    int(Qt.Key.Key_MediaStop): ACTION_MINIMAL_WIDGET,
    int(Qt.Key.Key_LaunchMedia): ACTION_OPEN_WIDGET,
}

MODIFIED_FUNCTION_KEY_ACTIONS: dict[int, str] = {
    VK_F8: ACTION_MINIMAL_WIDGET,
    VK_F9: ACTION_OPEN_WIDGET,
}


class RadioHotkeyManager(QObject):
    """Route safe global shortcuts without swallowing keys from Star Citizen.

    The Fn key has no standard Windows virtual-key code. Radio controls therefore
    react only to multimedia events generated by the keyboard firmware, never to
    bare F10/F11/F12. Widget open/minimise also has Ctrl+Alt+F9/F8 as a reliable
    fallback when a keyboard does not expose distinct Fn media events.
    """

    minimal_widget_requested = Signal()
    widget_requested = Signal()
    previous_requested = Signal()
    play_pause_requested = Signal()
    next_requested = Signal()

    POLL_INTERVAL_MS = 35
    DEDUPLICATION_SECONDS = 0.12

    def __init__(
        self,
        parent: QObject | None = None,
        *,
        enable_windows_polling: bool = True,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        super().__init__(parent)
        self._clock = clock
        self._last_action = ""
        self._last_action_time = -1.0
        keys = set(WINDOWS_VIRTUAL_KEY_ACTIONS) | set(MODIFIED_FUNCTION_KEY_ACTIONS)
        self._key_down = {virtual_key: False for virtual_key in keys}
        self._get_async_key_state = None
        self._windows_polling_active = False

        self.poll_timer = QTimer(self)
        self.poll_timer.setInterval(self.POLL_INTERVAL_MS)
        self.poll_timer.timeout.connect(self._poll_windows_keys)

        app = QApplication.instance()
        if os.name == "nt" and enable_windows_polling:
            try:
                get_async_key_state = ctypes.windll.user32.GetAsyncKeyState
                get_async_key_state.argtypes = [ctypes.c_int]
                get_async_key_state.restype = ctypes.c_short
                self._get_async_key_state = get_async_key_state
                self._windows_polling_active = True
                self.poll_timer.start()
            except (AttributeError, OSError):
                self._windows_polling_active = False

        if app is not None and not self._windows_polling_active:
            app.installEventFilter(self)

    @property
    def windows_polling_active(self) -> bool:
        return self._windows_polling_active

    def _is_down(self, virtual_key: int) -> bool:
        getter = self._get_async_key_state
        if getter is None:
            return False
        try:
            return bool(int(getter(virtual_key)) & 0x8000)
        except (OSError, TypeError, ValueError):
            return False

    def _poll_edge(self, virtual_key: int, action: str, enabled: bool = True) -> None:
        is_down = self._is_down(virtual_key)
        was_down = self._key_down.get(virtual_key, False)
        self._key_down[virtual_key] = is_down
        if enabled and is_down and not was_down:
            self.trigger_action(action)

    def _poll_windows_keys(self) -> None:
        if self._get_async_key_state is None:
            return
        for virtual_key, action in WINDOWS_VIRTUAL_KEY_ACTIONS.items():
            self._poll_edge(virtual_key, action)

        ctrl_alt = self._is_down(VK_CONTROL) and self._is_down(VK_MENU)
        for virtual_key, action in MODIFIED_FUNCTION_KEY_ACTIONS.items():
            self._poll_edge(virtual_key, action, enabled=ctrl_alt)

    def trigger_action(self, action: str) -> bool:
        if action not in {
            ACTION_MINIMAL_WIDGET,
            ACTION_OPEN_WIDGET,
            ACTION_PREVIOUS,
            ACTION_PLAY_PAUSE,
            ACTION_NEXT,
        }:
            return False
        now = self._clock()
        if action == self._last_action and now - self._last_action_time < self.DEDUPLICATION_SECONDS:
            return False
        self._last_action = action
        self._last_action_time = now
        if action == ACTION_MINIMAL_WIDGET:
            self.minimal_widget_requested.emit()
        elif action == ACTION_OPEN_WIDGET:
            self.widget_requested.emit()
        elif action == ACTION_PREVIOUS:
            self.previous_requested.emit()
        elif action == ACTION_PLAY_PAUSE:
            self.play_pause_requested.emit()
        else:
            self.next_requested.emit()
        return True

    def eventFilter(self, watched: QObject, event: QEvent) -> bool:  # noqa: N802
        del watched
        if event.type() != QEvent.Type.KeyPress:
            return False
        key_event = event if isinstance(event, QKeyEvent) else None
        if key_event is None or key_event.isAutoRepeat():
            return False

        key = int(key_event.key())
        modifiers = key_event.modifiers()
        required = Qt.KeyboardModifier.ControlModifier | Qt.KeyboardModifier.AltModifier
        if modifiers & required == required:
            if key == int(Qt.Key.Key_F8):
                return self.trigger_action(ACTION_MINIMAL_WIDGET)
            if key == int(Qt.Key.Key_F9):
                return self.trigger_action(ACTION_OPEN_WIDGET)

        action = QT_KEY_ACTIONS.get(key)
        return self.trigger_action(action) if action else False

    def shutdown(self) -> None:
        self.poll_timer.stop()
        app = QApplication.instance()
        if app is not None and not self._windows_polling_active:
            app.removeEventFilter(self)
        self._get_async_key_state = None
        self._windows_polling_active = False
